### ISSUE TITLE
tips: create an organization so someone does not have to create a DrawOnYourScreen4 in one year ;-)

### ISSUE THREAD

**Issue by oroulet** [daveprowse/DrawOnYourScreen3#2]

**Comment by daveprowse** [comment]
Thanks @oroulet . A GitHub Organization is on the tasklist, along with 20 other items!  :)
My primary goal is to get E.G.O. to accept the new version (after I lint it) and then move on with organizational tasks and invite people to join. 
I'll post an issue when it is ready. Thanks again!
