### ISSUE TITLE
Feature Request: external drawing clients

### ISSUE THREAD

**Issue by danielgomezrico** [daveprowse/DrawOnYourScreen3#3]
Hi

Thanks for the effort in following this, it’s wonderful.

I have a Samsung s6 lite, which has an s-pen.

I was thinking that it could be great if you could allow somehow drawers beside just the mouse as input for this. I can implement an app on my tablet and enable it to communicate with the server that draws and so be able to draw from the tablet itself.

The main thinking is that it's easier to draw using a pen than using a mouse.

I already built a server software that receives these inputs to draw on the screen, but since this already exists and has some history. It could be cool to use this as the server to draw instead of mine, which is pretty immature.

**Comment by daveprowse** [comment]
It's definitely on the roadmap. Touchscreen functionality would be great for all the people running Linux on Android-based tablets (or even iOS-based ones). It was set up by the original author as a branch 5 years ago but appears that it was quickly abandoned. In the new year I'll be testing out some options on an Android tablet and we'll see where it goes from there.

**Comment by vovche** [comment]
It will also be useful for touchscreen-enabled laptops
